engines/admin/config/routes.rb
Admin::Engine.routes.draw do
  resources :admin do
    member do
      get 'edit_avatar'
      put 'update_avatar'
    end
  end
  root to: 'home#index'
end

engines/admin/app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ::Admin::ApplicationController
    def edit_avatar
      @user = Auth::Admin.where(id: params[:id]).first
      redirect_to root_path, notice: "Can't find the resource" unless @user
    end

    def update
      debugger
      p "here"
    end
  end
end

engines/admin/app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    before_filter :restrict_aliens

    private

      def restrict_aliens
        unless admin_signed_in?
          flash[:notice] = "Access Restricted."
          redirect_to ::Auth::Engine.routes.url_helpers.root_path
        end
      end
  end
end

engines/admin/app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ApplicationController

    def index
    end

  end
end

engines/admin/app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
  end
end

engines/admin/app/views/admin/admin/edit_avatar.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'jquery.Jcrop.min' %>
  <%= stylesheet_link_tag 'jquery.Jcrop' %>
<% end %>

<h1>
  Go Ahead And Crop the Image as you like.
</h1>

<%= image_tag @user.avatar.url(:medium), id: 'cropbox' %>

<script>
  $(function(){
    $('#cropbox').Jcrop({
      onChange: update_crop,
      onSelect: update_crop
    });
  });

  function update_crop(coords){
    $('#crop_x').val(coords.x);
    $('#crop_y').val(coords.y);
    $('#crop_h').val(coords.h);
    $('#crop_w').val(coords.w);
  }
</script>

<%= form_for @user do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "Crop" %></p>
<% end %>

engines/admin/app/views/admin/home/index.html.erb
<h1>
  Welcome to Admin Panel !!
</h1>

<%= link_to (image_tag current_admin.avatar.url), edit_avatar_admin_path(current_admin) %>

<%= link_to 'Sign Out', destroy_session_path(current_admin), method: :delete %>
<%= link_to 'Edit Profile', edit_registration_path(current_admin) %>

engines/admin/app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= stylesheet_link_tag    "admin/application", :media => "all" %>
  <%= javascript_include_tag "admin/application" %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>